tab_adult:
  tables:
    table:
      primary_key: id

      fields:
        age: numerical
        workclass:
          type: categorical
          metrics:
            y_log: True
        fnlwgt: numerical
        education: categorical
        education-num: ordinal
        marital-status: categorical
        occupation: categorical
        relationship: categorical
        race: categorical
        sex: categorical
        capital-gain:
          type: numerical
          metrics:
            y_log: True
        capital-loss:
          type: numerical
          metrics:
            y_log: True
        hours-per-week: numerical
        native-country:
          type: categorical
          metrics:
            y_log: True
        income: categorical
