version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    json_formatter:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        class: pythonjsonlogger.jsonlogger.JsonFormatter

handlers:
    rich:
        class: rich.logging.RichHandler
        enable_link_path: False
        log_time_format: "[%X]"
        level: INFO

    # console:
    #     class: logging.StreamHandler
    #     level: INFO
    #     formatter: simple
    #     stream: ext://sys.stdout

    # Logs the console view as the user would see it
    # Sans the loading bars
    user:
        class: pasteur.utls.MlflowHandler
        name: user

        level: INFO
        formatter: simple

    # Debug and error log the exact output of the console
    debug:
        class: pasteur.utls.MlflowHandler
        name: debug

        level: DEBUG
        formatter: simple

    error:
        class: pasteur.utls.MlflowHandler
        name: error

        level: ERROR
        formatter: simple

loggers:
    anyconfig:
        level: DEBUG
        handlers: [debug, error]
        propagate: no

    numexpr.utils:
        level: NOTSET
        handlers: [debug, error]
        propagate: no

    IPKernelApp:
        level: NOTSET
        handlers: [debug, error]
        propagate: no

    blib2to3.pgen2.driver:
        level: NOTSET
        handlers: [debug, error]
        propagate: no

    py.warnings:
        level: DEBUG
        handlers: [debug, error]
        propagate: no

    kedro.io.data_catalog:
        level: NOTSET
        handlers: [debug, error]
        propagate: no

    kedro.io:
        level: NOTSET
        handlers: [debug, error]
        propagate: no

    kedro.extras.extensions.ipython:
        level: NOTSET
        handlers: [debug, error]
        propagate: no

    kedro.pipeline.node:
        level: NOTSET
        handlers: [debug, error]
        propagate: no

    kedro.config.common:
        level: NOTSET
        handlers: [debug, error]
        propagate: no

    kedro.framework.session.session:
        level: NOTSET
        handlers: [debug, error]
        propagate: no

    kedro.pipeline:
        level: NOTSET
        handlers: [debug, error]
        propagate: no

    dummy:
        level: NOTSET
        propagate: no

    git.cmd:
        level: NOTSET
        handlers: [debug, error]
        propagate: no

    pasteur.kedro.runner:
        level: NOTSET
        handlers: [rich, user, debug, error]
        propagate: no

root:
    level: NOTSET
    handlers: [rich, user, debug, error]
