version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    json_formatter:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
        class: pythonjsonlogger.jsonlogger.JsonFormatter

handlers:
    rich:
        class: rich.logging.RichHandler
        enable_link_path: False

    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: logs/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
        delay: True

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: logs/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8
        delay: True

loggers:
    anyconfig:
        level: INFO
        handlers: [info_file_handler, error_file_handler]
        propagate: no

    numexpr.utils:
        level: INFO
        handlers: [info_file_handler, error_file_handler]
        propagate: no

    IPKernelApp:
        level: INFO
        handlers: [info_file_handler, error_file_handler]
        propagate: no

    blib2to3.pgen2.driver:
        level: INFO
        handlers: [info_file_handler, error_file_handler]
        propagate: no

    py.warnings:
        level: INFO
        handlers: [info_file_handler, error_file_handler]
        propagate: no

    kedro.io.data_catalog:
        level: INFO
        handlers: [info_file_handler, error_file_handler]
        propagate: no

    kedro.io:
        level: INFO
        handlers: [info_file_handler, error_file_handler]
        propagate: no

    kedro.extras.extensions.ipython:
        level: INFO
        handlers: [info_file_handler, error_file_handler]
        propagate: no

    kedro.pipeline.node:
        level: INFO
        handlers: [info_file_handler, error_file_handler]
        propagate: no

    kedro.config.common:
        level: INFO
        handlers: [info_file_handler, error_file_handler]
        propagate: no

    kedro.framework.session.session:
        level: INFO
        handlers: [info_file_handler, error_file_handler]
        propagate: no

    kedro.pipeline:
        level: INFO
        handlers: [info_file_handler, error_file_handler]
        propagate: no

    pasteur.kedro.runner:
        level: INFO
        handlers: [rich]
        propagate: no

    dummy:
        level: INFO
        propagate: no

root:
    level: INFO
    handlers: [rich, info_file_handler, error_file_handler]
