default:
  ratios:
    wrk: 0.8
    ref: 0.2

  algs:
    privbayes:
      ep: 0.1
      e1: 0.3
      e2: 0.7
      theta: 4
      u: 1.3
      c: 1.5
      rebalance: True
      unbounded_dp: True
      random_init: False

    aim:
      dir: ${private_pgm}
      venv: ${private_pgm}/venv
      e: 1
      c: 1.5
      rebalance: True

    mrf:
      dir: ${privmrf}
      venv: ${privmrf}/venv
      e: 1.120
      c: 1.5
      rebalance: True
